themes/default/routes/admin.php
<?php
App::booted(function() {
	$namespace = 'Sudo\Theme\Http\Controllers\Admin';
	Route::namespace($namespace)->name('admin.')->prefix(config('app.admin_dir'))->middleware(['web', 'auth-admin'])->group(function() {
		// route chung cho cấu hình
		Route::name('settings.')->prefix('settings')->group(function() {
			// Cấu hình chung
			Route::match(['GET', 'POST'], 'general', 'SettingController@general')->name('general');
			// Cấu hình menu
			Route::match(['GET', 'POST'], 'menu', 'SettingController@menu')->name('menu');
			// Cấu hình trang chủ
			Route::match(['GET', 'POST'], 'home', 'SettingController@home')->name('home');
			// Cấu hình trang liên hệ
			Route::match(['GET', 'POST'], 'contact', 'SettingController@contact')->name('contact');
			// Cấu hình trang chủ
			Route::match(['GET', 'POST'], 'home', 'SettingController@home')->name('home');
			// Cấu hình tổng quan
			Route::match(['GET', 'POST'], 'overview', 'SettingController@overview')->name('overview');
			// Cấu hình email
			Route::match(['GET', 'POST'], 'email', 'SettingController@email')->name('email');
			// Cấu hình mã chuyển đổi
			Route::match(['GET', 'POST'], 'code', 'SettingController@code')->name('code');

			Route::post('mail_configs/test_mail','MailConfigController@testMail')->name('test_mail');
		});
		Route::name('icons.')->prefix('icons')->group(function() {
			Route::get('boxicons','IconController@boxicons')->name('boxicons');
			Route::get('design','IconController@design')->name('design');
			Route::get('dripicons','IconController@dripicons')->name('dripicons');
			Route::get('awesome','IconController@awesome')->name('awesome');
		});
	});
});

themes/default/routes/web.php
<?php
App::booted(function() {

	$namespace = 'Sudo\Theme\Http\Controllers\Web';
	Route::namespace($namespace)->name('app.')->middleware(['web'])->group(function() {
		Route::get('/test', 'TestController@index')->name('test');
		// Trang chủ
		Route::get('/', 'HomeController@index')->name('home');
		
		//chi tiet sp
		Route::get('/product', 'ProductController@index')->name('category');
		// Trang đơn
		// Trang đơn

		Route::get('/page/{slug}.html', 'PageController@show')->name('pages.show');
		// Tin tức
		Route::get('/blog/{slug}.html', 'PostController@show')->name('posts.show');
		// Danh mục tin tức
		Route::get('/blog/{slug?}', 'PostController@index')->name('post_categories.index');
		// chi tiết sản phẩm
		Route::get('{slug}.html', 'ProductController@show')->name('products.show');
		// danh mục sản phẩm
		Route::get('/{slug1?}/{slug2?}/{slug3?}','PostController@index')->name('product_categories.index');
	});
});

themes/default/resources/views/admin/custom/btn_check_email.blade.php
<div class="form-actions-inline">
	<div class="form-actions__group float-left">
		<button type="button" class="btn btn-sm btn-primary" id="test_mail_btn">@lang('Kiểm tra cấu hình mail')</button>
	</div>
</div>
<div id="test_mail_notificate">Đang kiểm tra. Vui lòng chờ giây lát!</div>
<script>
	$(document).ready(function() {
		$('body').on('click', '#test_mail_btn', function() {
			email = $('#test_mail').val();
			if (email == '') {
				alertText('@lang('Email nhận thư của bạn không được để trống')', 'warning');
			} else {
				data = $(this).closest('form').serialize()+'&email='+email;
				loadAjaxPost('{{route('admin.settings.test_mail')}}', data, {
					beforeSend: function(){
				        $('#test_mail_notificate').html('@lang('Đang kiểm tra. Vui lòng chờ giây lát!')');
				        $('#test_mail_notificate').show();
				    },
				    success:function(result){
				        $('#test_mail_notificate').html(result.message);
				    },
				    error: function (error) {
				        $('#test_mail_notificate').html('@lang('Có lỗi xảy ra! Lỗi:') <br>'+error.responseJSON.message);
				    }
				});
			}
		});
	});
</script>

themes/default/resources/views/admin/custom/file.blade.php
{{-- 
    @include('Form::base.image', [
        'name'              => $item['name'],
        'value'             => $item['value'],
        'required'          => $item['required'],
        'label'             => $item['label'],
        'title_btn'         => $item['title_btn'],
    ])
--}}

<div class="form-group row">
    @if ($has_full == true)
        <label for="{{ $name??'' }}" class="col-lg-12 col-form-label">@if($required==1) * @endif @lang($label??'')</label>
        <div class="col-lg-12">
    @else
        <label for="{{ $name??'' }}" class="col-lg-3 col-md-12 col-form-label text-right">@if($required==1) * @endif @lang($label??'')</label>
        <div class="col-lg-8 col-md-12">
    @endif
        <div class="image-box">
        	<button type="button" class="btn btn-primary btn-sm image-box__btn" 
                data-image="{{ route('media.index', [
                    'uploads' => 'single',
                    'field_id' => $name??'',
                    'only' => 'file'
                ]) }}"
            >@lang('Translate::form.choose') @lang($title_btn??$label??'')</button>
            <div class="image-box__content" id="{{$name??''}}_box">
                @php
                    $value = old($name)??$value;
                @endphp
                <div class="item" data-delete_box
                    data-image="{{ route('media.index', [
                        'uploads' => 'single',
                        'field_id' => $name??'',
                        'only' => 'file'
                    ]) }}"
                >
                    <img src="{{ getImage($value??'') }}" alt="">
                    <input type="hidden" value="{{ $value??'' }}" name="{{$name??''}}">
                    <span class="item-delete" data-delete_noremove><i class="fa fa-trash"></i></span>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            {{-- Click nút xóa ảnh thì sẽ trả về giá trị ảnh mặc định và value rỗng --}}
            $('body').on('click', '*[data-delete_noremove]', function() {
                $(this).closest('*[data-delete_box]').find('img').attr('src', '{{ getImageDefault() }}');
                $(this).closest('*[data-delete_box]').find('input').val('');
            });
            {{-- Nếu bắt buộc --}}
            @if ($required==1)
                $('body').on('click','button[type=submit]', function(e) {
                    if($('input[name={{$name??''}}]').length == 0) {
                        e.preventDefault();
                        $('#{{$name??''}}_box').find('.error').remove();
                        $('#{{$name??''}}_box').append(formHelper('@lang($label??$placeholder??$name??'') @lang('Translate::form.valid.no_empty')'));
                    }
                });
            @endif
        });
    </script>
</div>

themes/default/resources/views/admin/custom/note.blade.php
<div class="row">
	<p>* Lưu ý: Nếu bạn sử dụng Gmail miễn phí, tên đăng nhập và địa chỉ email gửi đi cần trùng nhau. Việc cấu hình sai thường dẫn tới email gửi đi bị đưa vào hộp thư rác của người nhận.</p>
</div>

themes/default/resources/views/admin/custom/param_email.blade.php
<div class="param-email">
	@foreach($param as $key => $value)
	<ul>
		<li>{!! $value !!}</li>
		<li>{{!! $key !!}}</li>
	</ul>
	@endforeach
</div>

themes/default/resources/views/admin/custom/sidebar.blade.php
<div class="settings-sidebar">
	<ul>
		<li @if($setting_name == 'overview') class="active" @endif><a href="{!! route('admin.settings.overview') !!}">@lang('Tổng quan')</a></li>
		<li @if($setting_name == 'email') class="active" @endif><a href="{!! route('admin.settings.email') !!}">@lang('Email')</a></li>
		<li @if($setting_name == 'code') class="active" @endif><a href="{!! route('admin.settings.code') !!}">@lang('Gắn mã chuyển đổi')</a></li>
	</ul>
</div>

themes/default/resources/views/admin/settings/form.blade.php
@extends('Core::layouts.app')

@section('title') @lang($module_name??'') @endsection
@section('content')

<form action="" class="form-horizontal" enctype="multipart/form-data" method="post">
	<div class="row">
		@include('Form::generate')
	</div>
</form>

@endsection

themes/default/resources/views/general/layouts/adminbar.blade.php
@if(Auth::guard('admin')->check())
    <div class="adminbar">
    	<style type="text/css">.adminbar {width: 100%;float: left;clear: both;background: #252627;color: #fff;font-family: 'arial', 'Sans-serif';}.adminbar-wrap {padding: 0 10px;}.adminbar-wrap ul {list-style: none;}.adminbar-wrap ul li {font-size: 13px;line-height: 32px;float: left;margin-right: 20px;font-weight: bold;}.adminbar-wrap ul li a {display: block;color: #ffffff;text-decoration: none;}</style>
    	<div class="container wrap adminbar-wrap">
	    	<ul>
	    		<li><a href="{!!route('admin.home')!!}">@lang('Trang quản trị')</a></li>
	    		{{--truyền link edit nội dung vào biến view có tên $admin_bar--}}
	    		@if(isset($admin_bar) && $admin_bar != '')
	    			<li><a href="{!!$admin_bar!!}">&#9998; @lang('Sửa nội dung này')</a></li>
	            @endif
	    	</ul>
    	</div>
    </div>
    <div style="clear: both;"></div>
@endif

themes/default/resources/views/general/layouts/seo.blade.php
{{-- 
	title: Lấy theo title tại biến MetaSeo
	Tiêu đề của trang
--}}
	<title>{{ $meta_seo['title'] ?? '' }}</title>
	
{{-- 
	description: Lấy theo description tại biến MetaSeo
	Mô tả của trang
--}}
@if(!empty($meta_seo['description']))
	<meta name="description" content="{{ $meta_seo['description'] ?? '' }}"/>
@endif

{{-- 
	robots: Lấy theo robots tại biến MetaSeo 
	có cho phép Google đánh index hay không
--}}
@if (isset($config_seo['robots']) && $config_seo['robots'] == '0')
	<meta name="robots" content="noindex,nofollow"/>
@elseif(isset($meta_seo['robots']) && !empty($meta_seo['robots']))
	<meta name="robots" content="{{ $meta_seo['robots'] ?? '' }}"/>
@endif

{{-- 
	canonical: Lấy theo url tại biến MetaSeo
	Dùng để định danh trang là duy nhất tại Domain
--}}
@if(!empty($meta_seo['url']))
	<link rel="canonical" href="{{ $meta_seo['url'] }}" />
@endif

{{-- 
	hreflang với website đa ngôn ngữ 
	$switch_language = [
		'lang_key_1' => 'lang_link_1',
		'lang_key_2' => 'lang_link_2',
	];
--}}
@if (isset($switch_language) && !empty($switch_language))
	@foreach ($switch_language as $lang_key => $lang_link)
		<link rel="alternate" hreflang="{{ $lang_key ?? '' }}" href="{{ $lang_link ?? '' }}">
	@endforeach
@endif

{{-- Facebook Meta Tags --}}
@if (!empty($meta_seo['locale']))
	<meta property="og:locale" content="{{ $meta_seo['locale'] }}" />
@endif
	<meta property="og:site_name" content="{{ config('app.name') }}" />
	<meta property="og:type" content="{{ $meta_seo['type'] ?? 'website' }}" />
@if(!empty($meta_seo['title']))
	<meta property="og:title" content="{{ $meta_seo['title'] ?? '' }}" />
@endif
@if(!empty($meta_seo['description']))
	<meta property="og:description" content="{{ $meta_seo['description'] }}" />
@endif
@if(!empty($meta_seo['url']))
	<meta property="og:url" content="{{ $meta_seo['url'] }}" />
@endif
@if(!empty($meta_seo['image']))
	<meta property="og:image" content="{{ $meta_seo['image'] }}" />
@endif

{{-- Twitter Meta Tags --}}
	<meta name="twitter:card" content="summary_large_image">
@if(!empty($meta_seo['title']))
	<meta name="twitter:title" content="{{ $meta_seo['title'] }}">
@endif
@if(!empty($meta_seo['description']))
	<meta name="twitter:description" content="{{ $meta_seo['description'] }}">
@endif
@if(!empty($meta_seo['image']))
	<meta name="twitter:image" content="{{ $meta_seo['image'] }}" />
@endif

themes/default/resources/views/web/home.blade.php
@extends('Default::web.layouts.app')
@section('content')
	<main class="site-main">
		<div class="container">
			<div class="site-main__banner">
				<div class="owl-carousel owl-theme">
                    <div class="item">
                		<a href="">
                			<img src="/assets/images/Bitmap.jpg" alt="">
                		</a>
                    </div>
                    <div class="item">
                		<a href="">
                			<img src="/assets/images/Bitmap.jpg" alt="">
                		</a>
                    </div>
                    <div class="item">
                		<a href="">
                			<img src="/assets/images/Bitmap.jpg" alt="">
                		</a>
                    </div>
                </div>		
			</div>
			<div class="site-main__images">
				<div class="list">
					<div class="list-item">
						<img src="/assets/images/Bitmap (1).jpg" alt="">
					</div>
					<div class="list-item">
						<img src="/assets/images/Bitmap Copy 3.jpg" alt="">
					</div>
					<div class="list-item">
						<img src="/assets/images/Bitmap (2).jpg" alt="">
					</div>
				</div>
			</div>
			<div class="site-main__slide">
                @if(isset($product_sellings) && count($product_sellings) > 0)
				    <h3>SẢN PHẨM NỔI BẬT</h3>
                    <div class="owl-carousel owl-theme">
                       @foreach ($product_sellings as $c => $product_selling)
                        <div class="item">
                        	<div class="item-images">
                        		<a href="">
                        			 <img src="{{ $product_selling->image }}" alt="">
                        		</a>
                        	</div>
                            <div class="item-info">
                            	<a href="">
                            		<h4>{{ $product_selling->name }}</h4>
                            	</a>
                            	<div class="item-info__price">
                            		<span>{{ formatPrice($product_selling->price) }}</span>
                            	</div>
                            </div>
                        </div>
                          @endforeach
                    </div>
                @endif
            </div>
            <div class="site-main__category">
            	<h3>DANH MỤC SẢN PHẨM</h3>
            	<div class="list">
            		<div class="row " style="justify-content: center;">
						@if(isset($categories) && count($categories) > 0)
						    @foreach ($categories as $c => $cate)
		            			<div class=" col-xl-2 col-lg-3 col-md-4 col-sm-6 ">
		            				<div class="list-product">
				            			<div class="list-product__image">
				            				<a href="">
				            					<img src="{{ $cate->getImage('medium') }}" >
				            				</a>
				            			</div>
				            			<div class="list-product__content">
				            				<a href=""> {!! $cate->name ?? '' !!}</a>
				            			</div>
				            		</div>
		            			</div>
		            		@endforeach
            			@endif
            		</div>           		
 	            </div>
            </div>
            <div class="site-main__producer">
            	<div class="top">
            		<div class="top-left">
	            		<h3>CÁC HÃNG</h3>
	            	</div>
	            	<div class="top-right">
	            		<span>Xem tất cả</span>
	            		<i class="fas fa-caret-right"></i>
	            	</div>
            	</div>
            	@if(isset($brands) && count($brands) > 0)
	            	<div class="table">
	            		@foreach ($brands as $brand)
						   <div class="band">
						    	<a href="#">
						    		<img class="lazy" src="{{ $brand->getImage('small') }}" alt="{{ getAlt($brand->image) }}" width="186" height="50">
						    	</a>
						    </div>
						@endforeach
	            	</div>
            	@endif
            </div>
        </div>
        <div class="site-main__center">
        	<div class="container">
                @if(isset($categories) && count($categories) > 0)
                    @foreach ($categories as $c => $cate)
                        @php
                            $childs = \Sudo\Ecommerce\Models\ProductCategory::where('parent_id', $cate->id)->limit(5)->get();
                            $product_ids = \DB::table('product_category_maps')
                                ->where('product_category_id', $cate->id)
                                ->pluck('product_id');
                            $products = \Sudo\Ecommerce\Models\Product::whereIn('id', $product_ids)->limit(6)->get();
                        @endphp
                		<div class="product">
        	            	<div class="product-title">
        	            		<div class="product-title__text">
        	            			<h3>{{ $cate->name }}</h3>
        	            		</div>
        	            		<div class="product-title__menu">
        	            			<ul>
                                        @foreach ($childs as $child)
                                            <li><a href="">{{ $child->name }}</a></li>
                                        @endforeach
                                        <li><a href="">Tất Cả Thiết Bị Dùng Pin</a></li>
                                        <li><a href=""><i class="fas fa-caret-right"></i></a></li>
        	            			</ul>
        	            		</div>
        	            	</div>
        	            	<div class="product-content">
                                @foreach ($products as $product)
            	            		<div class="product-content__item">
            	                    	<div class="images">
            	                    		<a href="">
            	                    			<img src="{{ $product->image }}" alt="">
            	                    		</a>
            	                    	</div>
            	                        <div class="info">
            	                        	<a href="">{{ $product->name }}</a>
            	        	               	<h3>{{ formatPrice($product->price) }}</h3>
            	                        </div>
            	                    </div>
                                @endforeach
        	            	</div>
        	            </div>
                    @endforeach
                @endif
        	</div>
        </div>
        <div class="container">
        	<div class="site-main__post">
            	<div class="title">
            		<div class="title-text">
            			<h3>KIẾN THỨC VÀ KĨ NĂNG</h3>
            		</div>
            		<div class="title-menu">
            			<ul>
            				<li><a href="">tư vấn sản phẩm</a></li>
            				<li class="in"><a href="">hướng dẫn sử dụng</a></li>
            				<li class="in"><a href="">chia sẻ kiến thức</a></li>
            				<li class="in"><a href=""><p>xem tất cả</p><i class="fas fa-caret-right"></i></a></li>
            			</ul>
            		</div>
            	</div>
            	<div class="content">
                    @foreach ($posts as $item)
                		<div class="content-item">
                        	<div class="content-item__images">
                        		<a href="">
                        			<img src="{{ $item->image}}" alt="">
                        		</a>
                        	</div>
                            <div class="content-item__info">
                            	<div class="top">
                            		<h4>{!! $item->name ?? '' !!}</h4>
                            	</div>
                            	<div class="center">
                            		<ul>
                            			<li><a href="">
                            				<img src="/assets/images/eye copy.png" alt="">
                            			</a></li>
                            			<li><a href=""><span>2569</span></a></li>
                            		</ul>
                            		<ul>
                            			<li><a href="">
                            				<img src="/assets/images/chat copy.png" alt="">
                            			</a></li>
                            			<li><a href=""><span>9</span></a></li>
                            		</ul>
                            	</div>
                            	<div class="bottom">
                                    <div class="text-box">
                                        <p>Máy hàn điện tử đang dần trở thành sự lựa chọn để thay thế cho những loại máy hàn truyền thống </p>
                                        <a href="">
                                        	<span>Xem thêm</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
            	</div>
	        </div>
        </div>
        <div class="site-main__bottom">
            <div class="container">
                <div class="review">
                    <div class="review-title">
                        <p>Review mới</p>
                    </div>
                    <div class="review-icon">
                        <p>Theo dõi trên</p>
                        <div class="icon-youtube">
                            <img src="/assets/images/youto.png" alt="">
                        </div>
                    </div>
                </div>
                <div class="banner">
                    <div class="col col-12 col-lg-8" style="padding-right: 20px;">
                        <div class="banner-left">
                            <img src="/assets/images/banner1.png" alt="">
                        </div>
                        <div class="banner-title">
                            <p>Review - Máy đục Stanley STHM5KH 1010W | SUPER MRO</p>
                        </div>
                    </div>
                    <div class="col col-12 col-lg-4">
                        <div class="banner-right">
                            <div class="box-right">
                                <img src="/assets/images/kim.png" alt="">
                                <p>Kìm cắt thủy lực ASAKI AK-0621 - 20mm</p>
                            </div>
                            <div class="box-right">
                                <img src="/assets/images/Bitmap (9).png" alt="">
                                <p>Tư vấn - Dụng cụ cầm tay - Những vật dụng cần thiết trong gia đình | SUPER MRO</p>
                            </div>
                            <div class="box-right-all">
                                <img src="/assets/images/Bitmap (10).png" alt="">
                                <p>So sánh - 3 máy khoan búa Bosch GBH 2-26DRE - Dewalt D25143 - Makita HR2630 | SUPER MRO</p>
                            </div>
                            <div class="box-right">
                                <img src="/assets/images/Bitmap Copy 30.png" alt="">
                                <p>Review - Bộ Khẩu Stanley 89-518-1 37 Chi Tiết | SUPER MRO</p>
                            </div>
                        </div>
                        <div class="buttom-all">
                            <p>Xem tất cả</p>
                            <i class="fas fa-caret-right"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</main>
@endsection

themes/default/resources/views/web/layouts/app.blade.php
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="vi" xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1"/>
    <link href="{{ asset('favicon.ico') }}" type="image/x-icon" rel="shortcut icon"/>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="agent" content="{{ checkAgent() }}">
    {{-- Các meta seo --}}
    @include('Default::general.layouts.seo')
    {{-- Cấu hình Asset --}}
    {!! Asset::renderHeader() !!}
    @yield('head')
  
    <title>Document</title>
</head>
<body>
	{{-- Thanh admin hiển thị cho quản trị --}}
    @include('Default::web.layouts.header')
	{{-- Nội dung trang --}}
    @yield('content')
    {{-- Cấu hình Asset --}}
    @include('Default::web.layouts.footer')
    {{-- @yield('foot') --}}
    {!! Asset::renderFooter() !!}
    {{-- @yield('head') --}}
    
</body>
</html/assets

themes/default/resources/views/web/layouts/footer.blade.php
<footer class="site-footer">
	<div class="site-footer__top">
		<div class="container">
			<div class="box">
				<div class="box-content">
					<div class="site-content__supe">
						<div class="title">
							<h4>Super MRO</h4>
						</div>
						<div class="info">
							<ul>
                                <li >
                                	<a href="">Mã số doanh nghiệp:
										<span>{{$config_general['code']}}</span>
									</a>
                                </li>
                                <li>
                                	<a href="">Văn phòng: 
										<span>{{$config_general['adre']}}</span>
									</a>
                                </li>
                                <li>
                                    <a href="">Kho hàng: 
										<span>{{$config_general['warehouse']}}</span>
									</a>
                                </li>
                                <li>
									<a href="">
										Tel: 
										<span>{{$config_general['phone']}}</span>
									</a>
								</li>
								<li>
									<a href="">
										E-mail: 
										<span>{{$config_general['email']}}</span>
									</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="site-content__info">
						<div class="title">
							<h4>Thông tin</h4>
						</div>
						<div class="nav">
							<ul>
								@php
                                    $nav = json_decode($config_menu['menu_info']) ?? [];
                                @endphp
                                @foreach ($nav as $element)
                                    <li>
                                        <a href="">{!!$element->name ?? '' !!}</a>
                                    </li>
                                @endforeach
							</ul>
						</div>
					</div>
					<div class="site-content__support">
						<div class="title">
							<h4>Hỗ trợ khách hàng</h4>
						</div>
						<div class="nav">
							<ul>
								@php
                                    $nav = json_decode($config_menu['menu_suppost']) ?? [];
                                @endphp
                                @foreach ($nav as $element)
                                    <li>
                                        <a href="">{!!$element->name ?? '' !!}</a>
                                    </li>
                                @endforeach
							</ul>
						</div>
					</div>
					<div class="site-content__account">
						<div class="title">
							<h4>Tài khoản</h4>
						</div>
						<div class="nav">
							<ul>
								@php
                                    $nav = json_decode($config_menu['menu_admin']) ?? [];
                                @endphp
                                @foreach ($nav as $element)
                                    <li>
                                        <a href="">{!!$element->name ?? '' !!}</a>
                                    </li>
                                @endforeach
							</ul>
						</div>
						<div class="connect">
							<h3>Kết nối với chúng tôi</h3>
							<ul>
								<li><a href="{{$config_general['facebook']}}"><img src="/assets/images/facebook.png" alt=""></a></li>
								<li><a href="{{$config_general['youtube']}}"><img src="/assets/images/Group 8.png" alt=""></a></li>
								<li><a href="{{$config_general['web']}}"><img src="/assets/images/wordpress.png" alt=""></a></li>
							</ul>
						</div>
						<div class="bottom">
							<img src="/assets/images/Bitmap (5).png" alt="">
						</div>
					</div>
					<div class="site-content__map">
						<div class="title">
							<h4>Hướng dẫn chỉ đường</h4>
						</div>
						<div class="center">
							<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3779.938592706119!2d105.67171981461522!3d18.66675138732404!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3139ce63742e981f%3A0x6449d97000dfe639!2zVG_DoCBuaMOgIEThuqd1IGtow60gUXVhbmcgVHJ1bmc!5e0!3m2!1svi!2s!4v1636970888966!5m2!1svi!2s" width="210" height="208" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="site-footer__bottom">
		<p>© 2013 Powered by IPComs Software. All Rights Reserved</p>
	</div>
</footer>

themes/default/resources/views/web/layouts/header.blade.php
<header class="site-header">
    <div class="header-pc ">
        <div class="site-header__content" >
            <div class="container">
                <div class="left">
                    <div class="left-logo">
                        <a href=""><img src="{{$config_general['logo_header_desktop']}}"></a>
                    </div>
                    <div class="left-search">
                        <form>
                            <input placeholder="Tìm kiếm">
                            <button><i class="fas fa-search"></i></button>
                        </form>
                    </div>
                </div>
                <div class="right">
                    <div class="right-quote">
                        <span>NHẬN BÁO GIÁ</span>
                        <i class="far fa-arrow-alt-to-bottom"></i>
                    </div>
                    <div class="right-register">
                        <h4>ĐĂNG KÝ</h4>
                        <p>NHẬN CATALOGUE</p>
                    </div>
                    <div class="right-cart">
                        <i class="fas fa-shopping-cart"></i>
                        <p>Giỏ hàng</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="site-main__breadecrumb">
            <div class="container">
                <div class="nav">
                    <a href=""><i class="fas fa-bars"></i></a>
                    <h4>Danh mục sản phẩm</h4>
                    <a href="" class="down"><i class="fas fa-caret-down"></i></a>
                </div>
                <div class="menu">
                    <ul>
                        <li><a href="">Trang chủ</a></li>
                        <li class="in"><a href="category">Sản phẩm</a></li>
                        <li><a href="">Blog</a></li>
                    </ul>
                </div>
                <div class="account">
                    <a href=""><span>Tài khoản</span></a>
                    <a href=""><i class="fas fa-caret-down"></i></a>
                </div>
            </div>
        </div>
    </div>
    <div class="header-overlay"></div>
    <div class="site-header__mobi" >
        <div class="container">
            <div class="header-content">
                <div class="left-mobi">
                    <a href="javascript:;">
                        <i class="fas fa-bars"></i>
                    </a>                        
                </div>
                <div class="right-mobi flex">
                    <a href="#">
                        <i class="far fa-user-circle"></i>
                    </a>
                    <a href="#">
                        <img src="/assets/images/cart.svg">
                    </a>

                    <a href="#" class="xxx">
                        <img src="/assets/images/search.svg">
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>